USE VENDA_CURSOS;

-- Exiba uma lista com os títulos dos cursos da Softblue e o tipo de curso ao lado. --
SELECT CURSO, TIPO FROM CURSO LEFT JOIN TIPO ON CURSO.CODIGO_TIPO = TIPO.CODIGO;

-- Exiba uma lista com os títulos dos cursos da Softblue, tipo do curso, nome do instrutor responsável pelo mesmo e telefone. -- 
SELECT CURSO.CURSO, TIPO.TIPO, INSTRUTOR.INSTRUTOR, INSTRUTOR.TELEFONE FROM CURSO INNER JOIN TIPO ON CURSO.CODIGO_TIPO = TIPO.CODIGO
INNER JOIN INSTRUTOR ON CURSO.CODIGO_INSTRUTOR = INSTRUTOR.CODIGO;

-- Exiba uma lista com o código e data e hora dos pedidos e os códigos dos cursos de cada pedido. -- 
SELECT PEDIDO.CODIGO, PEDIDO.DATA_PEDIDO, PEDIDO_DETALHE.CODIGO_CURSO FROM PEDIDO INNER JOIN PEDIDO_DETALHE ON
PEDIDO.CODIGO = PEDIDO_DETALHE.CODIGO_PEDIDO;

-- Exiba uma lista com o código e data e hora dos pedidos e os títulos dos cursos de cada pedido. -- 
SELECT PEDIDO.CODIGO, PEDIDO.DATA_PEDIDO, CURSO.CURSO FROM PEDIDO INNER JOIN PEDIDO_DETALHE ON
PEDIDO.CODIGO = PEDIDO_DETALHE.CODIGO_PEDIDO INNER JOIN CURSO ON CURSO.CODIGO = PEDIDO_DETALHE.CODIGO_CURSO;

-- Exiba uma lista com o código e data e hora dos pedidos, nome do aluno e os títulos dos cursos de cada pedido. -- 
SELECT PEDIDO.CODIGO, PEDIDO.DATA_PEDIDO, ALUNO.ALUNO, CURSO.CURSO FROM PEDIDO INNER JOIN PEDIDO_DETALHE ON
PEDIDO.CODIGO = PEDIDO_DETALHE.CODIGO_PEDIDO INNER JOIN CURSO ON CURSO.CODIGO = PEDIDO_DETALHE.CODIGO_CURSO
INNER JOIN ALUNO ON PEDIDO.CODIGO_ALUNO = ALUNO.CODIGO;

-- Crie uma visão que traga o título e preço somente dos cursos de programação da Softblue. -- 
CREATE VIEW  PRECO_CURSOS AS
SELECT CURSO, VALOR FROM CURSO WHERE CODIGO_TIPO = 2;

SELECT * FROM PRECO_CURSOS;

-- Crie uma visão que traga os títulos dos cursos, tipo do curso e nome do instrutor. -- 
CREATE VIEW RELACAO_CURSOS AS
SELECT CURSO.CURSO, TIPO.TIPO, INSTRUTOR.INSTRUTOR FROM CURSO INNER JOIN TIPO ON CURSO.CODIGO_TIPO = TIPO.CODIGO
INNER JOIN INSTRUTOR ON CURSO.CODIGO_INSTRUTOR = INSTRUTOR.CODIGO;

SELECT * FROM RELACAO_CURSOS;

-- Crie uma visão que exiba os pedidos realizados, informando o nome do aluno, data e código do pedido. -- 
CREATE VIEW PEDIDOS AS
SELECT ALUNO.ALUNO, PEDIDO.DATA_PEDIDO, PEDIDO.CODIGO FROM PEDIDO INNER JOIN ALUNO ON PEDIDO.CODIGO_ALUNO = ALUNO.CODIGO;

SELECT * FROM PEDIDOS;