USE CURSO_SQL;

DESCRIBE FUNCIONARIOS;

INSERT INTO FUNCIONARIOS (ID, NOME, SALARIO, DEPARTAMENTO) VALUES (1, 'Fernando', 1400, 'TI');
INSERT INTO FUNCIONARIOS (ID, NOME, SALARIO, DEPARTAMENTO) VALUES (2, 'Guilherme', 2500, 'Jurídico');
INSERT INTO FUNCIONARIOS (NOME, SALARIO, DEPARTAMENTO) VALUES ('Fábio', 1700, 'TI');
INSERT INTO FUNCIONARIOS (NOME, SALARIO, DEPARTAMENTO) VALUES ('José', 1800, 'Marketing');
INSERT INTO FUNCIONARIOS (NOME, SALARIO, DEPARTAMENTO) VALUES ('Isabela', 2200, 'Jurídico');

SELECT * FROM FUNCIONARIOS;
SELECT * FROM FUNCIONARIOS WHERE SALARIO > 2000;
SELECT * FROM FUNCIONARIOS WHERE NOME = 'JOSE';
SELECT * FROM FUNCIONARIOS WHERE NOME != 'JOSE';

UPDATE FUNCIONARIOS SET SALARIO = SALARIO * 1.1;
UPDATE FUNCIONARIOS SET SALARIO = SALARIO * 1.1 WHERE ID = 1;
SET SQL_SAFE_UPDATES = 0;
/* SET SQL_SAFE_UPDATES = 1; */
UPDATE FUNCIONARIOS SET SALARIO = SALARIO * 1.1;
UPDATE FUNCIONARIOS SET SALARIO = ROUND(SALARIO * 1.1, 2);

DELETE FROM FUNCIONARIOS WHERE ID = 4;

SELECT * FROM VEICULOS;

INSERT INTO VEICULOS (FUNCIONARIO_ID, VEICULO, PLACA) VALUES (1, 'STRADA', 'OYJ-8880');
INSERT INTO VEICULOS (FUNCIONARIO_ID, VEICULO, PLACA) VALUES (1, 'SAVEIRO', 'OYK-4455');

UPDATE VEICULOS SET FUNCIONARIO_ID = 5 WHERE ID = 2;

INSERT INTO SALARIOS (faixa, inicio, fim) VALUES ('Analista Jr.', 1000, 2000);
INSERT INTO SALARIOS (faixa, inicio, fim) VALUES ('Analista Pleno', 2000, 4000);

SELECT * FROM SALARIOS;

SELECT * FROM FUNCIONARIOS F WHERE F.SALARIO > 2000;

SELECT NOME AS FUNCIONÁRIO, SALARIO AS REMUNERAÇÃO FROM FUNCIONARIOS F WHERE F.SALARIO > 2000;

SELECT * FROM FUNCIONARIOS WHERE NOME = 'GUILHERME';
SELECT * FROM FUNCIONARIOS WHERE ID = 5;

SELECT * FROM FUNCIONARIOS WHERE NOME = 'GUILHERME' UNION SELECT * FROM FUNCIONARIOS WHERE ID = 5;
SELECT * FROM FUNCIONARIOS WHERE NOME = 'GUILHERME' UNION ALL SELECT * FROM FUNCIONARIOS WHERE ID = 2;