USE CURSO_SQL;

SELECT * FROM FUNCIONARIOS;
SELECT * FROM VEICULOS;

SELECT * FROM FUNCIONARIOS INNER JOIN VEICULOS ON VEICULOS.FUNCIONARIO_ID = FUNCIONARIOS.ID;
SELECT * FROM FUNCIONARIOS F INNER JOIN VEICULOS V ON V.FUNCIONARIO_ID = F.ID;

SELECT * FROM FUNCIONARIOS F LEFT JOIN VEICULOS V ON V.FUNCIONARIO_ID = F.ID;
SELECT * FROM FUNCIONARIOS F RIGHT JOIN VEICULOS V ON V.FUNCIONARIO_ID = F.ID;

INSERT INTO VEICULOS (VEICULO, PLACA) VALUES ('MOTO', 'SB-0001');

SELECT * FROM FUNCIONARIOS F LEFT JOIN VEICULOS V ON V.FUNCIONARIO_ID = F.ID UNION 
SELECT * FROM FUNCIONARIOS F RIGHT JOIN VEICULOS V ON V.FUNCIONARIO_ID = F.ID;

SELECT * FROM FUNCIONARIOS F LEFT JOIN VEICULOS V ON V.FUNCIONARIO_ID = F.ID UNION ALL 
SELECT * FROM FUNCIONARIOS F RIGHT JOIN VEICULOS V ON V.FUNCIONARIO_ID = F.ID;

CREATE TABLE cpfs
(
	ID INT UNSIGNED NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_CPF FOREIGN KEY (ID) REFERENCES FUNCIONARIOS (ID)
);

INSERT INTO CPFS (ID, CPF) VALUES (1, '111.111.111-11');
INSERT INTO CPFS (ID, CPF) VALUES (2, '222.222.222-22');
INSERT INTO CPFS (ID, CPF) VALUES (3, '333.333.333-33');
INSERT INTO CPFS (ID, CPF) VALUES (4, '444.444.444-44');
INSERT INTO CPFS (ID, CPF) VALUES (5, '555.555.555-55');

SELECT * FROM CPFS;

SELECT * FROM FUNCIONARIOS INNER JOIN CPFS ON FUNCIONARIOS.ID = CPFS.ID;
SELECT * FROM FUNCIONARIOS INNER JOIN CPFS USING (ID);

CREATE TABLE CLIENTES
(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(45) NOT NULL,
    QUEM_INDICOU INT UNSIGNED,
    PRIMARY KEY (ID),
    CONSTRAINT FK_QUEM_INDICOU FOREIGN KEY (QUEM_INDICOU) REFERENCES CLIENTES (ID)
);

INSERT INTO CLIENTES (ID, NOME, QUEM_INDICOU) VALUES (1, 'ANDRÉ', NULL);
INSERT INTO CLIENTES (ID, NOME, QUEM_INDICOU) VALUES (2, 'SAMUEL', 1);
INSERT INTO CLIENTES (ID, NOME, QUEM_INDICOU) VALUES (3, 'CARLOS', 2);
INSERT INTO CLIENTES (ID, NOME, QUEM_INDICOU) VALUES (4, 'RAFAEL', 1);

SELECT * FROM CLIENTES;

SELECT A.NOME AS CLIENTE, B.NOME AS "QUEM INDICOU" FROM CLIENTES A JOIN CLIENTES B ON A.QUEM_INDICOU = B.ID;
SELECT * FROM FUNCIONARIOS INNER JOIN VEICULOS ON VEICULOS.FUNCIONARIO_ID = FUNCIONARIOS.ID INNER JOIN CPFS ON CPFS.ID = FUNCIONARIOS.ID;

CREATE VIEW FUNCIONARIOS_A AS SELECT * FROM FUNCIONARIOS WHERE SALARIO >= 1700;
SELECT * FROM FUNCIONARIOS_A;

UPDATE FUNCIONARIOS SET SALARIO = 1500 WHERE ID = 3;

DROP VIEW FUNCIONARIOS_A;

CREATE VIEW FUNCIONARIOS_A AS SELECT * FROM FUNCIONARIOS WHERE SALARIO >= 2000;
SELECT * FROM FUNCIONARIOS_A;